// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db_gen

import (
	"context"
)

type Querier interface {
	InserOrderProduct(ctx context.Context, arg InserOrderProductParams) error
	InsertOrder(ctx context.Context, arg InsertOrderParams) error
	OrderFindByID(ctx context.Context, id string) (Orders, error)
	OrderProductFindByID(ctx context.Context, id string) (OrderProducts, error)
	ProductFetchWithOwner(ctx context.Context) ([]ProductFetchWithOwnerRow, error)
	ProductFindByID(ctx context.Context) (Products, error)
	ProductFindByIDs(ctx context.Context, ids []string) ([]Products, error)
	UpsertProduct(ctx context.Context, arg UpsertProductParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
	UserFindAll(ctx context.Context) ([]Users, error)
	UserFindByID(ctx context.Context, id string) (Users, error)
}

var _ Querier = (*Queries)(nil)
